#----------------------------------------------------------------------------
# Copyright Persistant Studios, SARL. All Rights Reserved.
# https://www.popcornfx.com/terms-and-conditions/
#----------------------------------------------------------------------------

set(FILES
    Include/PopcornFX/PopcornFXBus.h

    Source/Integration/Audio/PopcornFXAudioPool.h
    Source/Integration/Audio/PopcornFXAudioPool.cpp

    Source/Integration/Render/AtomIntegration/ParticleBuffers.h
    Source/Integration/Render/AtomIntegration/ParticleBuffers.cpp
    Source/Integration/Render/AtomIntegration/BillboardBatchDrawer.h
    Source/Integration/Render/AtomIntegration/BillboardBatchDrawer.cpp
    Source/Integration/Render/AtomIntegration/RibbonBatchDrawer.h
    Source/Integration/Render/AtomIntegration/RibbonBatchDrawer.cpp
    Source/Integration/Render/AtomIntegration/MeshBatchDrawer.h
    Source/Integration/Render/AtomIntegration/MeshBatchDrawer.cpp
    Source/Integration/Render/AtomIntegration/LightBatchDrawer.h
    Source/Integration/Render/AtomIntegration/LightBatchDrawer.cpp
    Source/Integration/Render/AtomIntegration/AtomFrameCollector.h
    Source/Integration/Render/AtomIntegration/AtomFrameCollector.cpp
    Source/Integration/Render/AtomIntegration/AtomFrameCollectorTypes.h
    Source/Integration/Render/AtomIntegration/AtomRendererCache.cpp
    Source/Integration/Render/AtomIntegration/AtomRendererCache.h
    Source/Integration/Render/AtomIntegration/AtomRenderDataFactory.h
    Source/Integration/Render/AtomIntegration/AtomRenderDataFactory.cpp
    Source/Integration/Render/AtomIntegration/AtomPipelineCache.h
    Source/Integration/Render/AtomIntegration/AtomPipelineCache.cpp
    Source/Integration/Render/AtomIntegration/PopcornFXFeatureProcessor.h
    Source/Integration/Render/AtomIntegration/PopcornFXFeatureProcessor.cpp

    Source/Integration/Render/CameraInfo.h

    Source/Integration/Managers/EmittersManager.cpp
    Source/Integration/Managers/EmittersManager.h
    Source/Integration/Managers/RenderManager.cpp
    Source/Integration/Managers/RenderManager.h
    Source/Integration/Managers/BroadcastManager.cpp
    Source/Integration/Managers/BroadcastManager.h
    Source/Integration/Managers/MediumCollectionManager.cpp
    Source/Integration/Managers/MediumCollectionManager.h
    Source/Integration/Managers/StatsManager.cpp
    Source/Integration/Managers/StatsManager.h
    Source/Integration/Managers/WindManager.cpp
    Source/Integration/Managers/WindManager.h
    Source/Components/Emitter/PopcornFXEmitterGameComponent.cpp
    Source/Components/Emitter/PopcornFXEmitterGameComponent.h
    Source/Components/Emitter/PopcornFXEmitterRuntime.cpp
    Source/Components/Emitter/PopcornFXEmitterRuntime.h
    Source/Components/Emitter/PopcornFXEmitter.cpp
    Source/Components/Emitter/PopcornFXEmitter.h
    Source/Components/Attributes/PopcornFXAttributeList.cpp
    Source/Components/Attributes/PopcornFXAttributeList.h
    Source/Components/Attributes/TrackView/PopcornFXTrackViewAttributeGameComponent.cpp
    Source/Components/Attributes/TrackView/PopcornFXTrackViewAttributeGameComponent.h
    Source/Components/Attributes/TrackView/PopcornFXTrackViewAttribute.cpp
    Source/Components/Attributes/TrackView/PopcornFXTrackViewAttribute.h
    Source/Components/Samplers/PopcornFXSamplerAnimTrack.cpp
    Source/Components/Samplers/PopcornFXSamplerAnimTrack.h
    Source/Components/Samplers/PopcornFXSamplerAnimTrackGameComponent.cpp
    Source/Components/Samplers/PopcornFXSamplerAnimTrackGameComponent.h
    Source/Components/Samplers/PopcornFXSamplerImage.cpp
    Source/Components/Samplers/PopcornFXSamplerImage.h
    Source/Components/Samplers/PopcornFXSamplerImageGameComponent.cpp
    Source/Components/Samplers/PopcornFXSamplerImageGameComponent.h
    Source/Components/Samplers/PopcornFXSkinnedMesh.cpp
    Source/Components/Samplers/PopcornFXSkinnedMesh.h
    Source/Components/Samplers/PopcornFXSamplerShape.cpp
    Source/Components/Samplers/PopcornFXSamplerShape.h
    Source/Components/Samplers/PopcornFXSamplerShapeGameComponent.cpp
    Source/Components/Samplers/PopcornFXSamplerShapeGameComponent.h
    Source/Components/Samplers/PopcornFXSamplerText.cpp
    Source/Components/Samplers/PopcornFXSamplerText.h
    Source/Components/Samplers/PopcornFXSamplerTextGameComponent.cpp
    Source/Components/Samplers/PopcornFXSamplerTextGameComponent.h
    Source/Components/Helpers/PopcornFXHelperLoopEmitterGameComponent.cpp
    Source/Components/Helpers/PopcornFXHelperLoopEmitterGameComponent.h
    Source/Components/Helpers/PopcornFXHelperProfilerGameComponent.cpp
    Source/Components/Helpers/PopcornFXHelperProfilerGameComponent.h
    Source/Integration/Preloader/PopcornFXPreloader.cpp
    Source/Integration/Preloader/PopcornFXPreloader.h
    Source/Integration/Preloader/PopcornFXRendererLoader.cpp
    Source/Integration/Preloader/PopcornFXRendererLoader.h
    Source/Integration/ResourceHandlers/ImageResourceHandler.cpp
    Source/Integration/ResourceHandlers/ImageResourceHandler.h
    Source/Integration/ResourceHandlers/MeshResourceHandler.cpp
    Source/Integration/ResourceHandlers/MeshResourceHandler.h
    Source/Asset/PopcornFXAssetHandler.cpp
    Source/Asset/PopcornFXAssetHandler.h
    Source/Asset/PopcornFXAsset.h
    Source/ScriptCanvas/PopcornFXBroadcastNodeable.cpp
    Source/ScriptCanvas/PopcornFXBroadcastNodeable.h
    Source/ScriptCanvas/PopcornFXBroadcastNodeable.ScriptCanvasNodeable.xml
    Source/Integration/PopcornFXStartUpdate.cpp
    Source/Integration/PopcornFXStartUpdate.h
    Source/Integration/PopcornFXStopUpdate.cpp
    Source/Integration/PopcornFXStopUpdate.h
    Source/Integration/PopcornFXUtils.h
    Source/Integration/Startup/PopcornFxPlugins.cpp
    Source/Integration/Startup/PopcornFxPlugins.h
    Source/Integration/File/FileSystemController_O3DE.cpp
    Source/Integration/File/FileSystemController_O3DE.h
)
